# Generated by Django 2.0.4 on 2018-04-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightdata',
            name='title_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
