# Generated by Django 2.0.4 on 2018-04-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_weightdata_title_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightdata',
            name='check_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='weightdata',
            name='weight_value',
            field=models.CharField(default='', max_length=200),
        ),
    ]
