# Generated by Django 2.0.4 on 2018-04-17 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_remove_weightdata_check_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightdata',
            name='check_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
