# Generated by Django 2.0.4 on 2018-04-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_weightdata_check_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightdata',
            name='title_text',
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='check_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='weightdata',
            name='weight_value',
            field=models.FloatField(),
        ),
    ]
